# Generated by Django 5.1.1 on 2024-11-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_is_flash_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_flash_sale',
            field=models.BooleanField(default=False),
        ),
    ]
